# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class Sstart < Formula
  desc "Sstart: secure start for cloud-native secrets"
  homepage "https://github.com/securestart/sstart"
  url "https://github.com/securestart/sstart/archive/refs/tags/v0.0.8.tar.gz"
  sha256 "12eedfd69f37297a248eb95eb3350579932ea47876528c04aeae520bfd106b4c"
  license "Apache-2.0"

  def install
    bin.install "sstart"
  end
end
