# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class Sstart < Formula
  desc "Sstart: secure start for cloud-native secrets"
  homepage "https://github.com/securestart/sstart"
  url "https://github.com/securestart/sstart/archive/refs/tags/v0.0.9.tar.gz"
  sha256 "496bb13b6a06680df9f077936d46985334139d04c926ea5321391c4dc492cb8c"
  license "Apache-2.0"

  on_macos do
  end

  on_linux do
  end

  def install
    bin.install Dir["**/sstart"].find { |f| File.file?(f) } => "sstart"
  end
end
